Add AWS S3 storage
ton-community/gamefi-sdk pull request #4
Opened 2023-10-02 14:27 UTC by jokly

PR for the issue #3 
[Telegram Profile](https://t.me/jokly32)

2023-10-04 08:07 UTC, krigga requested changes

2023-10-04 08:07 UTC, krigga commented on package-lock.json
This project uses yarn, so please remove this

2023-10-04 08:07 UTC, krigga commented on package.json
> +    "@aws-sdk/client-s3": "^3.421.0",
There is a new version, please update

2023-10-04 08:07 UTC, krigga commented on src/storage.ts
> +import { S3 } from "@aws-sdk/client-s3"
Please use single quotes and add a semicolon

2023-10-04 08:07 UTC, krigga commented on src/storage.ts
> +import { AwsCredentialIdentity } from "@aws-sdk/types";
Since this type is not needed (see below), please remove this

2023-10-04 08:07 UTC, krigga commented on src/storage.ts
> +            credentials: {
This object can be written as just
```ts
{
                accessKeyId,
                secretAccessKey,
}
```
(no need to put `!` and do type assertions)

2023-10-04 08:07 UTC, krigga commented on src/storage.ts
> +    async uploadFile(contents: Buffer): Promise<string> {
Please add 2 missing semicolons in this method

2023-10-04 09:47 UTC, jokly commented
Thank you for the review. Fixed the problems

2023-10-04 18:36 UTC, krigga requested changes
I'm sorry, I forgot to tell you the first time, this storage option also needs to be added here https://github.com/ton-community/gamefi-sdk/blob/e56f2bcedfc08aca52c8d2e3deb92d5704541133/src/sdk.ts#L18-L30

2023-10-05 07:01 UTC, jokly commented
Done :)

2023-10-10 11:18 UTC, krigga approved these changes
LGTM, thank you for your contribution!

2023-10-10 11:18 UTC, merged